# Generated by Django 5.2.6 on 2024-05-19 14:20

from django.db import migrations

def add_eur_currency(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    Currency.objects.create(code='EUR', name='Euro')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_eur_currency),
    ]